### PR TITLE
Update phpunit

### PR DESCRIPTION
**Pull request by pascalheidmann**

### CODE REVIEW

**Comment by pascalheidmann** [comment]
@marc-mabe can you have a look at this? :)

**Comment by marc-mabe** [comment]
Hi @pascalheidmann ,
Why do you remove supported PHP versions only to upgrade PHPunit?

**Comment by pascalheidmann** [comment]
@marc-mabe these PHP versions are way beyond their EOL, and PHPUnit 9 therefore requires at least PHP 7.3 (also already EOL)

**Comment by marc-mabe** [comment]
Hi @pascalheidmann,
EOL PHP Versions means it's not supported by PHP anymore but there are distros having much longer (payed) support plans including PHP.
Anyway upgrading the minimum PHP Version requires some kind of benefit which I don't see here.
If you want to improve or simplify the tests which requires the new version I'm open for it.

**Comment by marc-mabe** [comment]
PHPUnit is now upgraded to 9.6 - the latest version with support for PHP 7.4

**Pull request closed without merging**
